version: "3"
services:
 php:
   build: .
   ports:
     - "8888:80"
   volumes:
     - ./src:/var/www/html
   depends_on:
     - database

 database:
   image: mysql:8
   command: --default-authentication-plugin=mysql_native_password
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: docker_php
     MYSQL_USER: user
     MYSQL_PASSWORD: password
   volumes:
     - database:/var/lib/mysql
     
 phpmyadmin:
   image: phpmyadmin
   ports:
     - 8080:80
   environment:
     - PMA_ARBITRARY=1
   depends_on:
     - database

volumes:
 database:
